services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: payments
      MONGO_INITDB_ROOT_PASSWORD: paymentsroot
volumes:
  mongo-data:
